/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import CrudManager.CatalogloanrecordManager;
import CrudManager.CatalogrecordManager;
import Domain.Catalogloanrecord;
import Domain.Catalogrecord;
import Service.JDBCImplement.JDBCMainConfiguration;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author Adrian
 */
public class JIFManageCatalogloan extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFManageCatalogloan
     */
    JDBCMainConfiguration jdbc = new JDBCMainConfiguration();
    table loan = new table();
    combobox cus = new combobox();
    combobox emp = new combobox();
    combobox catre = new combobox();
    
    
     HashMap<String,Integer> custMap=cus.getCustMap();
  HashMap<String,Integer> empMap=emp.getEmpMap();
 HashMap<String,Integer>catrecMap=cus.getcatrecMap();
    
    
    
    public JIFManageCatalogloan() {
        initComponents();
        loan.fillCatalogloanJTable(record_table, "");
       
        fillcucombobox();
       fillempcombobox();
       fillcatreccombobox();
    
        
        try {
            jdbc.getConnection();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(JIFManageCatalogloan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        custcombo1 = new javax.swing.JComboBox<>();
        findVal_box = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        empcombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        catcombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        idj = new javax.swing.JTextField();
        create_tb = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        update_bt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        del_bt = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        record_table = new javax.swing.JTable();
        code_tb = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        recievdateChooserCombo1 = new com.toedter.calendar.JDateChooser();
        loandateChooserCombo2 = new com.toedter.calendar.JDateChooser();
        cat_id = new javax.swing.JLabel();
        cus_id = new javax.swing.JLabel();
        emp_id = new javax.swing.JLabel();

        setClosable(true);

        custcombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custcombo1ActionPerformed(evt);
            }
        });

        findVal_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                findVal_boxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                findVal_boxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                findVal_boxKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Catalog loan Record");

        empcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empcomboActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("catalog");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Customer");

        catcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catcomboActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Employee");

        idj.setText(" ");

        create_tb.setText("Create");
        create_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_tbActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Loan Date");

        update_bt.setText("Update");
        update_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Recieved Date");

        del_bt.setText("Delete");
        del_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_btActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Loan Code");

        record_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Catalog", "Customer", "Loan Date ", "Recieved Date", "Loan Code", "Employee"
            }
        ));
        record_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                record_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(record_table);

        code_tb.setText(" ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Search");

        cat_id.setText("ID");

        cus_id.setText("ID");

        emp_id.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(emp_id))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(idj, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cus_id))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loandateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(recievdateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(custcombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(catcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(51, 51, 51)
                                        .addComponent(code_tb))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cat_id)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(findVal_box, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(create_tb)
                .addGap(29, 29, 29)
                .addComponent(update_bt)
                .addGap(18, 18, 18)
                .addComponent(del_bt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(idj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cat_id))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cus_id))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(emp_id))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(catcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(custcombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(empcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(loandateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(recievdateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(findVal_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(code_tb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(update_bt)
                        .addComponent(del_bt))
                    .addComponent(create_tb))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findVal_boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findVal_boxKeyPressed
        record_table.setModel(new DefaultTableModel(null, new Object[]{"id", "Catalog", "Customer", "Loan Date ", "Recieved Date", "Loan Code", "Employee"}));
        loan.fillCatalogloanJTable(record_table, "");
    }//GEN-LAST:event_findVal_boxKeyPressed

    private void findVal_boxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findVal_boxKeyReleased
           record_table.setModel(new DefaultTableModel(null, new Object[]{"id", "Catalog", "Customer", "Loan Date ", "Recieved Date", "Loan Code", "Employee"}));
        loan.fillCatalogloanJTable(record_table, "");
    }//GEN-LAST:event_findVal_boxKeyReleased

    private void findVal_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findVal_boxKeyTyped
        record_table.setModel(new DefaultTableModel(null, new Object[]{"id", "Catalog", "Customer", "Loan Date ", "Recieved Date", "Loan Code", "Employee"}));
        loan.fillCatalogloanJTable(record_table, "");
    }//GEN-LAST:event_findVal_boxKeyTyped

    private void create_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_tbActionPerformed

        int id=Integer.parseInt(idj.getText().trim());
     //    Integer catalogrecord_id=catcombo.getText().trim();
     //    Integer cus_id=custcombo1.getText().trim();
    //   Integer emp_id=empcombo.getText().trim();
    //    Integer pub_id=pubcombo.getText().trim();
    //    String conditionstatement=condi_tb.getText();
        String code=code_tb.getText().trim();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String releasedate = dateFormat.format(recievdateChooserCombo1.getDate());
        String loandate = dateFormat.format(loandateChooserCombo2.getDate());
       
     
        // Catalogrecord anCatalogrecord=new Catalogrecord(id,title,releasedate,conditionstatement,code,genre_id,doc_id,author_id,pub_id);

        CatalogloanrecordManager CatalogloanMgr = new CatalogloanrecordManager();
        // CatalogloanMgr.addCatalogloanrecord(anCatalogloanrecord);

        record_table.setModel(new DefaultTableModel(null, new Object[]{"id", "Catalog", "Customer", "Loan Date ", "Recieved Date", "Loan Code", "Employee"}));
        loan.fillCatalogloanJTable(record_table, "");

        JOptionPane.showMessageDialog(rootPane, "Successful Save", "", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_create_tbActionPerformed

    private void update_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btActionPerformed

        try{
            Catalogloanrecord anCatalogloan=new Catalogloanrecord();
            anCatalogloan.setId(Integer.parseInt(idj.getText()));
            //    anCatalogrecord.setTitle(title.getText());
            //    anCatalogrecord.setGenre_id(genrecombo.getText());
            //    anCatalogrecord.setDocumenttype(doccombo.getText());
            //    anCatalogrecord.setAuthor(authcombo1.getText());
            //   anCatalogrecord.setPublisher(pubcombo.getText());
            anCatalogloan.setLoancode(code_tb.getText());
    
         
    anCatalogloan.setLoandate(loandateChooserCombo2.getDate());
    
     anCatalogloan.setRecieveddate(recievdateChooserCombo1.getDate());


            
            CatalogloanrecordManager CatalogloanMgr=new CatalogloanrecordManager ();
            CatalogloanMgr.updateCatalogloanrecord(anCatalogloan);

             record_table.setModel(new DefaultTableModel(null, new Object[]{"id", "Catalog", "Customer", "Loan Date ", "Recieved Date", "Loan Code", "Employee"}));
        loan.fillCatalogloanJTable(record_table, "");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_update_btActionPerformed

    private void del_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_btActionPerformed
        if(idj.getText()=="")
        {
            JOptionPane.showMessageDialog(rootPane, "No Catalogrecord Id selected", "", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(idj.getText()!="")
        {
            try{
                int CatalogloanId=Integer.parseInt(idj.getText());
                   CatalogloanrecordManager CatalogloanMgr = new CatalogloanrecordManager();
                CatalogloanMgr.deleteCatalogloanrecord(CatalogloanId);
                JOptionPane.showMessageDialog(rootPane, "Catalogrecord Deleted", "", JOptionPane.INFORMATION_MESSAGE);

                record_table.setModel(new DefaultTableModel(null, new Object[]{"id", "Catalog", "Customer", "Loan Date ", "Recieved Date", "Loan Code", "Employee"}));
        loan.fillCatalogloanJTable(record_table, "");

            }
            catch(Exception ex)
            {
                ex.printStackTrace();
                // logger.error(ex.getMessage());
            }
        }
    }//GEN-LAST:event_del_btActionPerformed

    
    private void ShowItem(int rowIndex){
     DefaultTableModel model=(DefaultTableModel)record_table.getModel();
     idj.setText(model.getValueAt(rowIndex, 0).toString());
     
     Date loandate=null;
     Date releaseddate=null;
        try {
             releaseddate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
            loandate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 3).toString());
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(JIFManageCatalogloan.class.getName()).log(Level.SEVERE, null, ex);
        }
    loandateChooserCombo2.setDate(loandate);
     recievdateChooserCombo1.setDate(releaseddate);
    }
    
    
    private void record_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_record_tableMouseClicked
        int rowIndex= record_table.getSelectedRow();
        ShowItem(rowIndex);
        
        DefaultTableModel model=(DefaultTableModel)record_table.getModel();
        idj.setText(model.getValueAt(rowIndex, 0).toString());
     //catcombo.1
     //custcombo1.2
     //empcombo.6
     
        
     Date loandate=null;
     Date releaseddate=null;
        try {
             releaseddate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
            loandate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 3).toString());
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(JIFManageCatalogloan.class.getName()).log(Level.SEVERE, null, ex);
        }
    loandateChooserCombo2.setDate(loandate);
     recievdateChooserCombo1.setDate(releaseddate);
    
        code_tb.setText(model.getValueAt(rowIndex, 5).toString());
        
    }//GEN-LAST:event_record_tableMouseClicked

    private void catcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catcomboActionPerformed
            try{
        
         int c_id = custMap.get(custcombo1.getSelectedItem().toString());
        cus_id.setText(String.valueOf(c_id));
        
        }catch(Exception ex){
        
        java.util.logging.Logger.getLogger(JIFManageCatalogrecord.class.getName()).log(Level.SEVERE, null, ex);
        
        }         
    }//GEN-LAST:event_catcomboActionPerformed

    private void empcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empcomboActionPerformed
         try{
        
         int e_id = empMap.get(empcombo.getSelectedItem().toString());
        emp_id.setText(String.valueOf(e_id));
        
        }catch(Exception ex){
        
        java.util.logging.Logger.getLogger(JIFManageCatalogrecord.class.getName()).log(Level.SEVERE, null, ex);
        
        }
    }//GEN-LAST:event_empcomboActionPerformed

    private void custcombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custcombo1ActionPerformed
         try{
        
         int cust_id = custMap.get(custcombo1.getSelectedItem().toString());
        cus_id.setText(String.valueOf(cust_id));
        
        }catch(Exception ex){
        
        java.util.logging.Logger.getLogger(JIFManageCatalogrecord.class.getName()).log(Level.SEVERE, null, ex);
        
        }
    }//GEN-LAST:event_custcombo1ActionPerformed

   
    
    
   public void  fillcucombobox(){
     
        for(String pcode : custMap.keySet())
       {
   
   custcombo1.addItem(pcode);
       }
     
     
     }   
      public void fillempcombobox(){
      
           for(String doctypeName : empMap.keySet())
       {
   
   empcombo.addItem(doctypeName);
       }
      
      }   
   public void fillcatreccombobox(){
   
       for(String genreName : catrecMap.keySet())
       {
   
   catcombo.addItem(genreName);
       }
   }  




    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cat_id;
    private javax.swing.JComboBox<String> catcombo;
    private javax.swing.JTextField code_tb;
    private javax.swing.JButton create_tb;
    private javax.swing.JLabel cus_id;
    private javax.swing.JComboBox<String> custcombo1;
    private javax.swing.JButton del_bt;
    private javax.swing.JLabel emp_id;
    private javax.swing.JComboBox<String> empcombo;
    private javax.swing.JTextField findVal_box;
    private javax.swing.JTextField idj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser loandateChooserCombo2;
    private com.toedter.calendar.JDateChooser recievdateChooserCombo1;
    public static javax.swing.JTable record_table;
    private javax.swing.JButton update_bt;
    // End of variables declaration//GEN-END:variables
}
