/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import CrudManager.AuthorManager;
import Domain.Author;
import Service.JDBCImplement.JDBCMainConfiguration;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static presentation.LCMSPresntation.logger;

/**
 *
 * @author Adrian
 */
public class JIFManageAuthor extends javax.swing.JInternalFrame {

    
    
          Connection con;
          Statement stmt;
     
          JDBCMainConfiguration jdbc = new JDBCMainConfiguration();
    
    /**
     * Creates new form JIFManageAuthor
     */
          
table Author=new table();

    public JIFManageAuthor() {
        initComponents();
        
        Author.fillAuthorJtable(author_table, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdp1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstnameJtf1 = new javax.swing.JTextField();
        lastnameJtf2 = new javax.swing.JTextField();
        authcodJtf1 = new javax.swing.JTextField();
        createjButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        author_table = new javax.swing.JTable();
        update_bt = new javax.swing.JButton();
        del_bt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        findVal_box = new javax.swing.JTextField();
        idj = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Author");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Author Code");

        firstnameJtf1.setText(" ");

        lastnameJtf2.setText(" ");

        authcodJtf1.setText(" ");

        createjButton1.setText("ADD");
        createjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createjButton1ActionPerformed(evt);
            }
        });

        author_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "First Name", "Last Name", "Author Code"
            }
        ));
        author_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                author_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(author_table);

        update_bt.setText("Update");
        update_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btActionPerformed(evt);
            }
        });

        del_bt.setText("Delete");
        del_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_btActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Search");

        findVal_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                findVal_boxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                findVal_boxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                findVal_boxKeyTyped(evt);
            }
        });

        idj.setText(" ");

        jdp1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp1.setLayer(firstnameJtf1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp1.setLayer(lastnameJtf2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp1.setLayer(authcodJtf1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp1.setLayer(createjButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp1.setLayer(update_bt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp1.setLayer(del_bt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp1.setLayer(findVal_box, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp1.setLayer(idj, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdp1Layout = new javax.swing.GroupLayout(jdp1);
        jdp1.setLayout(jdp1Layout);
        jdp1Layout.setHorizontalGroup(
            jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jdp1Layout.createSequentialGroup()
                        .addGroup(jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdp1Layout.createSequentialGroup()
                                .addGroup(jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel4))
                                .addGap(37, 37, 37)
                                .addGroup(jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstnameJtf1)
                                    .addComponent(lastnameJtf2)
                                    .addComponent(authcodJtf1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jdp1Layout.createSequentialGroup()
                                .addComponent(createjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(update_bt)
                                .addGap(18, 18, 18)
                                .addComponent(del_bt))
                            .addGroup(jdp1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(idj, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(findVal_box, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))))))
        );
        jdp1Layout.setVerticalGroup(
            jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp1Layout.createSequentialGroup()
                .addGroup(jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(firstnameJtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lastnameJtf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(authcodJtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createjButton1)
                            .addComponent(update_bt)
                            .addComponent(del_bt))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp1Layout.createSequentialGroup()
                        .addGap(0, 79, Short.MAX_VALUE)
                        .addGroup(jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(findVal_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createjButton1ActionPerformed
         
           //   int id=Integer.parseInt(idj.getText().trim());
        String fname=firstnameJtf1.getText().trim();
        String lname=lastnameJtf2.getText().trim();
       
        String authorcode=authcodJtf1.getText().trim();
        
        Author anAuthor=new Author(fname,lname,authorcode);
      
        AuthorManager authorMgr = new AuthorManager();
        authorMgr.addAuthor(anAuthor,"HIBER");
         JOptionPane.showMessageDialog(rootPane, "Successful Save", "", JOptionPane.INFORMATION_MESSAGE);
         
         author_table.setModel(new DefaultTableModel(null, new Object[]{"id","First Name","Last Name","Author Code"}));
         Author.fillAuthorJtable(author_table,"");
    }//GEN-LAST:event_createjButton1ActionPerformed

    private void author_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_author_tableMouseClicked
        int rowIndex= author_table.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)author_table.getModel();
 idj.setText(model.getValueAt(rowIndex, 0).toString());
 firstnameJtf1.setText(model.getValueAt(rowIndex, 1).toString());
  lastnameJtf2.setText(model.getValueAt(rowIndex, 2).toString()); 
  authcodJtf1.setText(model.getValueAt(rowIndex, 3).toString());
    }//GEN-LAST:event_author_tableMouseClicked

    private void findVal_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findVal_boxKeyTyped
        
        author_table.setModel(new DefaultTableModel(null, new Object[]{"id","First Name","Last Name","Author Code"}));
       Author.fillAuthorJtable(author_table, findVal_box.getText());
    }//GEN-LAST:event_findVal_boxKeyTyped

    private void findVal_boxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findVal_boxKeyReleased
       author_table.setModel(new DefaultTableModel(null, new Object[]{"id","First Name","Last Name","Author Code"}));
       Author.fillAuthorJtable(author_table, findVal_box.getText().trim());
    }//GEN-LAST:event_findVal_boxKeyReleased

    private void findVal_boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findVal_boxKeyPressed
        author_table.setModel(new DefaultTableModel(null, new Object[]{"id","First Name","Last Name","Author Code"}));
        Author.fillAuthorJtable(author_table, findVal_box.getText());
    }//GEN-LAST:event_findVal_boxKeyPressed

    private void update_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btActionPerformed
       
        try{
        Author theAuthor=new Author();
       theAuthor.setId(Integer.parseInt(idj.getText()));
        theAuthor.setFname(firstnameJtf1.getText());
        theAuthor.setLname(lastnameJtf2.getText());
        theAuthor.setAuthorcode(authcodJtf1.getText());
        
               
        AuthorManager authMgr=new AuthorManager();
        authMgr.updateAuthor(theAuthor,"HIBER");
        
        author_table.setModel(new DefaultTableModel(null, new Object[]{"id","First Name","Last Name","Author Code"}));
         Author.fillAuthorJtable(author_table,"");
        }
        catch(Exception ex)
                {
                  ex.printStackTrace();
                }
    }//GEN-LAST:event_update_btActionPerformed

    private void del_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_btActionPerformed
        if(idj.getText()=="")
        {
            JOptionPane.showMessageDialog(rootPane, "No Author Id selected", "", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(idj.getText()!="")
        {
            try{
                int authorId=Integer.parseInt(idj.getText());
                AuthorManager authoMgr=new AuthorManager();
                authoMgr.deleteAuthor(Author.class, authorId,"HIBER");
                JOptionPane.showMessageDialog(rootPane, "Author Deleted", "", JOptionPane.INFORMATION_MESSAGE);

                author_table.setModel(new DefaultTableModel(null, new Object[]{"id","First Name","Last Name","Author Code"}));
                Author.fillAuthorJtable(author_table,"");

            }
            catch(Exception ex)
            {
                ex.printStackTrace();
                logger.error(ex.getMessage());
            }
        }
    }//GEN-LAST:event_del_btActionPerformed

   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authcodJtf1;
    public static javax.swing.JTable author_table;
    private javax.swing.JButton createjButton1;
    private javax.swing.JButton del_bt;
    private javax.swing.JTextField findVal_box;
    private javax.swing.JTextField firstnameJtf1;
    private javax.swing.JTextField idj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDesktopPane jdp1;
    private javax.swing.JTextField lastnameJtf2;
    private javax.swing.JButton update_bt;
    // End of variables declaration//GEN-END:variables
}
