/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

/**
 *
 * @author Adrian
 */
public class MainMenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuForm
     */
    public MainMenuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jdp1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        author_tb = new javax.swing.JMenuItem();
        pub_tb = new javax.swing.JMenuItem();
        doctype_tb = new javax.swing.JMenuItem();
        genre_tb = new javax.swing.JMenuItem();
        ddoctype = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        addcatrec_tb = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        addloan_tb = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();
        addcustomer_tb = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        viewemp_tb = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jdp1Layout = new javax.swing.GroupLayout(jdp1);
        jdp1.setLayout(jdp1Layout);
        jdp1Layout.setHorizontalGroup(
            jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1021, Short.MAX_VALUE)
        );
        jdp1Layout.setVerticalGroup(
            jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );

        jMenu3.setText("Manage Records");

        author_tb.setText("Manage Authors");
        author_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                author_tbActionPerformed(evt);
            }
        });
        jMenu3.add(author_tb);

        pub_tb.setText("Manage Publishers");
        pub_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pub_tbActionPerformed(evt);
            }
        });
        jMenu3.add(pub_tb);

        doctype_tb.setText("Manage Document Type");
        doctype_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctype_tbActionPerformed(evt);
            }
        });
        jMenu3.add(doctype_tb);

        genre_tb.setText("Manage Genre");
        genre_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genre_tbActionPerformed(evt);
            }
        });
        jMenu3.add(genre_tb);

        ddoctype.setText("Manage Document Types");

        jMenuItem13.setText("View");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        ddoctype.add(jMenuItem13);

        jMenuItem15.setText("Update");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        ddoctype.add(jMenuItem15);

        jMenuItem16.setText("Delete");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        ddoctype.add(jMenuItem16);

        jMenu3.add(ddoctype);

        jMenu6.setText("Manage Catalog Records");

        jMenuItem17.setText("View");
        jMenu6.add(jMenuItem17);

        addcatrec_tb.setText("Add");
        addcatrec_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcatrec_tbActionPerformed(evt);
            }
        });
        jMenu6.add(addcatrec_tb);

        jMenuItem19.setText("Update");
        jMenu6.add(jMenuItem19);

        jMenuItem20.setText("Delete");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem20);

        jMenu3.add(jMenu6);

        jMenu7.setText("Manage Catalog loans");

        jMenuItem21.setText("View");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem21);

        addloan_tb.setText("Add");
        addloan_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addloan_tbActionPerformed(evt);
            }
        });
        jMenu7.add(addloan_tb);

        jMenuItem23.setText("Update");
        jMenu7.add(jMenuItem23);

        jMenuItem24.setText("Delete");
        jMenu7.add(jMenuItem24);

        jMenu3.add(jMenu7);

        jMenuBar1.add(jMenu3);
        jMenuBar1.add(jMenu2);

        jMenu8.setText("Manage Stakeholders");

        jMenu12.setText("Manage Customers");

        jMenuItem29.setText("View");
        jMenu12.add(jMenuItem29);

        addcustomer_tb.setText("Add");
        addcustomer_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcustomer_tbActionPerformed(evt);
            }
        });
        jMenu12.add(addcustomer_tb);

        jMenuItem31.setText("Update");
        jMenu12.add(jMenuItem31);

        jMenuItem32.setText("Delete");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem32);

        jMenu8.add(jMenu12);

        viewemp_tb.setText("Manage Employees");

        jMenuItem25.setText("View");
        viewemp_tb.add(jMenuItem25);

        jMenuItem27.setText("Update");
        viewemp_tb.add(jMenuItem27);

        jMenuItem28.setText("Delete");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        viewemp_tb.add(jMenuItem28);

        jMenu8.add(viewemp_tb);

        jMenuBar1.add(jMenu8);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp1)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void author_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_author_tbActionPerformed
        JIFManageAuthor addAuthInterface = new JIFManageAuthor();

        addAuthInterface.setVisible(true);

        jdp1.add(addAuthInterface);
        addAuthInterface.moveToFront();

        this.validate();
        this.repaint();

    }//GEN-LAST:event_author_tbActionPerformed

    private void pub_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pub_tbActionPerformed
       JIFManagePublisher addPublisherInterface = new JIFManagePublisher();

        addPublisherInterface.setVisible(true);

        jdp1.add(addPublisherInterface);
        addPublisherInterface.moveToFront();

        this.validate();
        this.repaint();
    }//GEN-LAST:event_pub_tbActionPerformed

    private void doctype_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctype_tbActionPerformed
        JIFManageDocType addGenreInterface = new JIFManageDocType();

        addGenreInterface.setVisible(true);

        jdp1.add(addGenreInterface);
        addGenreInterface.moveToFront();

        this.validate();
        this.repaint();

    }//GEN-LAST:event_doctype_tbActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void genre_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genre_tbActionPerformed
       JIFManageGenre addDocumenttypeInterface = new JIFManageGenre();

        addDocumenttypeInterface.setVisible(true);

        jdp1.add(addDocumenttypeInterface);
        addDocumenttypeInterface.moveToFront();

        this.validate();
        this.repaint();
    }//GEN-LAST:event_genre_tbActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void addcatrec_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcatrec_tbActionPerformed
    
        JIFManageCatalogrecord addCatlogrecordInterface = new JIFManageCatalogrecord();

        addCatlogrecordInterface.setVisible(true);

        jdp1.add(addCatlogrecordInterface);
        addCatlogrecordInterface.moveToFront();

        this.validate();
        this.repaint();
    }//GEN-LAST:event_addcatrec_tbActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void addloan_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addloan_tbActionPerformed
        
          JIFManageCatalogloan addCatalogloanInterface = new JIFManageCatalogloan();

        addCatalogloanInterface.setVisible(true);

        jdp1.add(addCatalogloanInterface);
        addCatalogloanInterface.moveToFront();

        this.validate();
        this.repaint();
    }//GEN-LAST:event_addloan_tbActionPerformed

    private void addcustomer_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcustomer_tbActionPerformed
       JIFManageCustomer addCustomerInterface = new JIFManageCustomer();

        addCustomerInterface.setVisible(true);

        jdp1.add(addCustomerInterface);
        addCustomerInterface.moveToFront();

        this.validate();
        this.repaint();
    }//GEN-LAST:event_addcustomer_tbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addcatrec_tb;
    private javax.swing.JMenuItem addcustomer_tb;
    private javax.swing.JMenuItem addloan_tb;
    private javax.swing.JMenuItem author_tb;
    private javax.swing.JMenu ddoctype;
    private javax.swing.JMenuItem doctype_tb;
    private javax.swing.JMenuItem genre_tb;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JDesktopPane jdp1;
    private javax.swing.JMenuItem pub_tb;
    private javax.swing.JMenu viewemp_tb;
    // End of variables declaration//GEN-END:variables
}
