/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import static com.github.adrian3xl.sharedinterface.CheckTime.formattedDate;

/**
 *
 * @author Adrian
 */
public class MainMenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuForm
     */
    public MainMenuForm() {
        initComponents();
         showdatetime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jdp1 = new javax.swing.JDesktopPane();
        time_tb = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        author_tb = new javax.swing.JMenuItem();
        pub_tb = new javax.swing.JMenuItem();
        doctype_tb = new javax.swing.JMenuItem();
        genre_tb = new javax.swing.JMenuItem();
        addcatrec_tb = new javax.swing.JMenuItem();
        addloan_tb = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        customer_tb = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setVisible(true);

        time_tb.setBackground(new java.awt.Color(255, 0, 0));
        time_tb.setText("time/date");

        jdp1.setLayer(time_tb, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdp1Layout = new javax.swing.GroupLayout(jdp1);
        jdp1.setLayout(jdp1Layout);
        jdp1Layout.setHorizontalGroup(
            jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp1Layout.createSequentialGroup()
                .addContainerGap(858, Short.MAX_VALUE)
                .addComponent(time_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jdp1Layout.setVerticalGroup(
            jdp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(time_tb, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(692, Short.MAX_VALUE))
        );

        jMenu3.setText("Manage Records");

        author_tb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        author_tb.setText("Manage Authors");
        author_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                author_tbActionPerformed(evt);
            }
        });
        jMenu3.add(author_tb);

        pub_tb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        pub_tb.setText("Manage Publishers");
        pub_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pub_tbActionPerformed(evt);
            }
        });
        jMenu3.add(pub_tb);

        doctype_tb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        doctype_tb.setText("Manage Document Type");
        doctype_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctype_tbActionPerformed(evt);
            }
        });
        jMenu3.add(doctype_tb);

        genre_tb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        genre_tb.setText("Manage Genre");
        genre_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genre_tbActionPerformed(evt);
            }
        });
        jMenu3.add(genre_tb);

        addcatrec_tb.setText("Manage Catalog Records");
        addcatrec_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcatrec_tbActionPerformed(evt);
            }
        });
        jMenu3.add(addcatrec_tb);

        addloan_tb.setText("Manage Catalog Loan Record");
        addloan_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addloan_tbActionPerformed(evt);
            }
        });
        jMenu3.add(addloan_tb);

        jMenuBar1.add(jMenu3);
        jMenuBar1.add(jMenu2);

        jMenu8.setText("Manage Stakeholders");

        customer_tb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        customer_tb.setText("Manage Customers");
        customer_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_tbActionPerformed(evt);
            }
        });
        jMenu8.add(customer_tb);

        jMenuBar1.add(jMenu8);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp1)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void author_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_author_tbActionPerformed
        JIFManageAuthor addAuthInterface = new JIFManageAuthor();

        addAuthInterface.setVisible(true);

        jdp1.add(addAuthInterface);
        addAuthInterface.moveToFront();

        this.validate();
        this.repaint();

    }//GEN-LAST:event_author_tbActionPerformed

    private void pub_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pub_tbActionPerformed
       JIFManagePublisher addPublisherInterface = new JIFManagePublisher();

        addPublisherInterface.setVisible(true);

        jdp1.add(addPublisherInterface);
        addPublisherInterface.moveToFront();

        this.validate();
        this.repaint();
    }//GEN-LAST:event_pub_tbActionPerformed

    private void doctype_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctype_tbActionPerformed
        JIFManageDocType addGenreInterface = new JIFManageDocType();

        addGenreInterface.setVisible(true);

        jdp1.add(addGenreInterface);
        addGenreInterface.moveToFront();

        this.validate();
        this.repaint();

    }//GEN-LAST:event_doctype_tbActionPerformed

    private void genre_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genre_tbActionPerformed
       JIFManageGenre addDocumenttypeInterface = new JIFManageGenre();

        addDocumenttypeInterface.setVisible(true);

        jdp1.add(addDocumenttypeInterface);
        addDocumenttypeInterface.moveToFront();

        this.validate();
        this.repaint();
    }//GEN-LAST:event_genre_tbActionPerformed

    private void addcatrec_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcatrec_tbActionPerformed
    
        JIFManageCatalogrecord addCatlogrecordInterface = new JIFManageCatalogrecord();

        addCatlogrecordInterface.setVisible(true);

        jdp1.add(addCatlogrecordInterface);
        addCatlogrecordInterface.moveToFront();

        this.validate();
        this.repaint();
    }//GEN-LAST:event_addcatrec_tbActionPerformed

    private void addloan_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addloan_tbActionPerformed
        
          JIFManageCatalogloan addCatalogloanInterface = new JIFManageCatalogloan();

        addCatalogloanInterface.setVisible(true);

        jdp1.add(addCatalogloanInterface);
        addCatalogloanInterface.moveToFront();

        this.validate();
        this.repaint();
    }//GEN-LAST:event_addloan_tbActionPerformed

    private void customer_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_tbActionPerformed
       JIFManageCustomer addCustomerInterface = new JIFManageCustomer();

        addCustomerInterface.setVisible(true);

        jdp1.add(addCustomerInterface);
        addCustomerInterface.moveToFront();

        this.validate();
        this.repaint();
    }//GEN-LAST:event_customer_tbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuForm().setVisible(true);
            }
        });
    }
    
    
    
       public void showdatetime(){
    
     time_tb.setText(formattedDate);
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addcatrec_tb;
    private javax.swing.JMenuItem addloan_tb;
    private javax.swing.JMenuItem author_tb;
    private javax.swing.JMenuItem customer_tb;
    private javax.swing.JMenuItem doctype_tb;
    private javax.swing.JMenuItem genre_tb;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdp1;
    private javax.swing.JMenuItem pub_tb;
    private javax.swing.JLabel time_tb;
    // End of variables declaration//GEN-END:variables
}
